### ISSUE TITLE
Error on importing react-images-upload.

### ISSUE THREAD

**Issue by ahmedtehseen** [JakeHartnell/react-images-upload#2] opened 2017-08-15 11:49 UTC
When I import react-images-upload from node_modules Like that.

**import ImageUploader from 'react-images-upload';**

It gives me error.

_**Uncaught SyntaxError: Unexpected token export**_

**Comment by michaelryancaputo** [comment] 2017-08-28 21:46
Same issue here, I think you need to specify an entry file in your package.json

**Comment by baaraak** [comment] 2017-09-01 21:52
Hey guys, 
It's my first module so I don't really know how to handles git issues properly :-) 
I tried to reproduce this bug with several react boilerplates/projects with no success...

@michaelryancaputo 
My entry file is index.js in the root directory.
Even then I still need to add an entry to package.json?

**Comment by ahmedtehseen** [comment] 2017-09-02 10:49
@michaelryancaputo  thanks man I will definitely try this out.
@baaraak  @michaelryancaputo  thanks both of you.

**Comment by fazial** [comment] 2017-09-06 07:41
I'm as well having the same issue, does anybody has the solution?

**Comment by michaelryancaputo** [comment] 2017-09-06 12:04
@baaraak You're right, I checked, if you're using index.js you don't need to specify a `main` file in package.json.

**Comment by emreturkis** [comment] 2017-09-25 13:32
same issue here. Are there any solutions?

**Comment by kingarawana** [comment] 2017-09-27 14:02
The problem is because of this line. `export default ReactImageUploadComponent;`

Change it to `module.exports = ReactImageUploadComponent;`

(node_modules/react-images-upload/index.js)

In my project babel doesn't process files in node_modules. So I'm guessing `export default..` is not supported.

**Comment by JakeHartnell** [comment] 2020-02-22 22:36
Should be fixed now. Let me know if this is still an issue.

**Closed by JakeHartnell** 2020-02-22 22:36 UTC
