### ISSUE TITLE
User can choose multiple files when singleImage is true 

### ISSUE THREAD

**Issue by donalmurtagh** [JakeHartnell/react-images-upload#53] opened 2018-06-29 15:12 UTC
The markup for the `input` element always has an attribute `multiple="multiple"` but this attribute should be omitted if the `singleImage` prop is set to true.

Also, the `singleImage` attribute is not documented.

**Comment by Boussama** [comment] 2018-07-09 16:47
This new issue is a duplicate of #45

**Closed** 2018-07-09 18:17 UTC
