### ISSUE TITLE
multiple image selection when singleImage is true

### ISSUE THREAD

**Issue by Boussama** [JakeHartnell/react-images-upload#45] opened 2018-06-05 08:18 UTC
Wrong behavior, when singleImage is true user should not be able to select multiple image to upload, not just on the component UI.

**Comment by donalmurtagh** [comment] 2018-07-02 08:59
This is a duplicate of #53. I've submitted a PR to fix this #54

**Comment by Boussama** [comment] 2018-07-09 16:47
This issue was submitted first and can't be a duplicate to a new issue.

**Closed** 2018-07-09 18:17 UTC

**Comment by donalmurtagh** [comment] 2018-07-10 11:17
@Boussama by "duplicate", I mean they are both covering the same topic

**Comment by brionmario** [comment] 2018-07-13 12:47
Is this fixed yet? I have the version 1.2.0 and the issue is still there.
